zk:
  version: 3.4.8
  mirror: http://ftp.meisei-u.ac.jp/mirror/apache/dist
  data_dir: /var/lib/zookeeper
  install_dir: "/etc"
  tick_time: 2000
zk_cluster_info:
  apkafka01.docl.nic:
    zk_id: 1
  apkafka02.docl.nic::
    zk_id: 2
  apkafka03.docl.nic::
    zk_id: 3
  apkafka04.docl.nic::
    zk_id: 4
  apkafka05.docl.nic::
    zk_id: 5
