kafka:
  upgrade: false
  version: 0.10.0.0
  scala_version: 2.11
  mirror: http://ftp.meisei-u.ac.jp/mirror/apache/dist
  data_dir: /var/lib/kafka
  install_dir: "/opt"
# This does not have to be every Zookeeper host, but the more the better
#  by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zk'] }}" # This does not have to be every Zookeeper host
zk_client_port: 2181 # Should be set properly if not using Vagrant
system_file_limit: 40960
file_max: 100000
heap_size_gb: 10
jmx_port: 9099
kafka_version: "kafka_{{ scala_version }}-{{ version }}"
# e.g., 
#kafka_version: kafka_2.11-0.10.0.0
