kafka:
  version: 0.10.0.0
  scala_version: 2.11
  mirror: http://ftp.meisei-u.ac.jp/mirror/apache/dist
  data_dir: /var/lib/kafka
  install_dir: "/opt"
# This does not have to be every Zookeeper host, but the more the better
#  by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zk'] }}" # This does not have to be every Zookeeper host
zk_client_port: 2181 # Should be set properly if not using Vagrant
kafka_cluster_info:
  APkafka01.docl.nic:
    broker_id: 1
  APkafka02.docl.nic::
    broker_id: 2
  APkafka03.docl.nic::
    broker_id: 3
  APkafka04.docl.nic::
    broker_id: 4
  APkafka05.docl.nic::
    broker_id: 5

